# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9009ad0847d1e475231cdcaa484922768d3ebf4879ff384062bbd53338207c63b586f0bdcdf2ff78b173c561c92f63eb83857313c31d3cece57413cb68491feb

test:
  secret_key_base: 175550dc2d82ac5f28196ec645081c70c4a87e7b98f98352703436af370a4446dc716a0d5ed2aa6e904dde257e6ca045c4dd84f5a470d5984b5b373416567117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
